### PR TITLE
testnet-0.15.1

### PR DESCRIPTION
**Pull request by jasonxh**

### CODE REVIEW

**Comment by jachen-sh** [comment]
This build would show up on the public github packages no?

**Comment by jasonxh** [comment]
> This build would show up on the public github packages no?

Yes everything in this repo is. The sui git tag is public too so anyone can build it.

**Comment by jachen-sh** [comment]
Would that be an issue since Mysten wants no press or publicity on it?

**Comment by jasonxh** [comment]
> Would that be an issue since Mysten wants no press or publicity on it?

I don't think so. After all they're running an open-source project. They just don't want to proactively promote it just yet, which we aren't doing anyway.

**Pull request merged**
